feat(User login):
chekwas88/JavaNiche pull request #2
Opened 2019-09-02 13:56 UTC by chekwas88

### What does this PR do?

* configure jest for testing and circleci for continuous integration

### Description of Task to be completed?
* create methods for users to login via their github account
* create loading screen and login screen
* style login screen
* write tests for feature
### Any background context you want to provide?

N/A

### What are the relevant Github issues?

N/A

### Questions:

N/A

2019-09-03 21:27 UTC, Musigwa-zz requested changes
Great work @chekwas88, kindly check out the comments that I left on some lines of codes. Also, take a look at the following [package](https://github.com/zetachang/react-native-dotenv), it may help to control well your environment variables.

2019-09-03 21:27 UTC, Musigwa-zz commented on .env
> +CC_TEST_REPORTER_ID=fb9aa7d1a8b4c0ed1b9cd43ad24e0fb4e1b390f09fb300870019bd10603fb160
@chekwas88  kindly ignore `.env` file since it always contains sensitive data that shouldn't be revealed. You can set these as environment variables.

2019-09-03 21:27 UTC, Musigwa commented on src/github/getGithubToken.js
> +const CLIENT_ID = 'f9d99e0e7e1bc66deb13';
Kindly keep these in `environment variables`

2019-09-04 08:35 UTC, chekwas88 commented on .env
> +CC_TEST_REPORTER_ID=fb9aa7d1a8b4c0ed1b9cd43ad24e0fb4e1b390f09fb300870019bd10603fb160
thought I ignored it... will do that ASAP

2019-09-04 11:04 UTC, merged